export const MAPBOX_ACCESS_TOKEN = 'MAPBOX_ACCESS_TOKEN'
export const GOOGLE_ACCESS_TOKEN = 'GOOGLE_ACCESS_TOKEN'
export const GEOCODING_PROVIDER = 'GEOCODING_PROVIDER'

export const TOKEN = 'MT_TOKEN'
export const REFRESH_TOKEN = 'MT_REFRESH_TOKEN'
export const LAST_REFRESH_TOKEN_TIMESTAMP = 'MT_LAST_REFRESH_TOKEN_TIMESTAMP'
export const TOKEN_EXPIRES_TIME = 'MT_TOKEN_EXPIRES_TIME'
export const IS_AUTH = 'MT_IS_AUTH'
export const USER_TYPE = 'MT_USER_TYPE'

export const DEFAULT_TOKEN_EXPIRES = 365
export const USER_INFO = 'MT_USER_INFO'